#!/bin/sh
#
# this is a shorthand for
# - erasing CUL
# - flashing the new firmware
# - restarting CUL
#

#
PROGRAMMER=dfu-programmer
MCU=at90usb162
IMAGE=CULeth.hex

# ---------
if [ ! -f $IMAGE ]; then
	echo "$IMAGE: No such file." >&2
	exit 1
fi
P="$PROGRAMMER $MCU"
$P erase && $P flash $IMAGE && $P start
